language: go
sudo: false
go:
  - 1.5
  - 1.6
  - tip
before_install:
  - npm install -g bower
  - bower install
install: make bindata
script:
  - go get -t -v ./...
  - go tool vet .
  - go test -v -race ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
env:
  global:
    secure: "SVmjHeardtVTpyjYQG++hwKtDqmkvnSZ/IYOECuLB4cJYlavzZMey2mNMaUTuJEs8LoH1dhyHGuzJ1+5Wd6FhWTLadK+1C6H+93NEkIVX7IIJ3PAbmbe1Erk4MvupCQ68WiIiBO+FexQH9A3JsNcUyjbQNZWw9pDJryJ5h4ZQOEzxuZeVVUpxDU0jfYzC9ERg06GvVBSYnyf/XMOCVh/3scprayyaCS7hq4OJ4awyEfrID6jIbJnrT5NHBbJO7YL5IpQepBh025IJrqf8JY0cgQtBHhZ9gchUkipo+Zj35roUZddjfxjnOU9B2kEz4NY4sd9qW1SQ/xTXKnVkPsOBLBhRcNEeN2bofZWQp+LP570W6IZlZNf1JuUVt6+pNQOlC0RPqhGns2/mgf+tUIf8OnOezffcXbVHIi1CzOr+9DJGfuRlN3905Sl4PEub02+pZEfmOjsK6oON7Z+/l2Zyy4Lmr4xkW71YSw9QmtDAm+VsAOOMrCzhi1cN7nxnyXtPUQw6SDePSUYNu16olv/KFiNnvUj0nOYeh3vGrjSuRycJwrw1BoAd37Cn5zjzUtcUWdZuUAaEccEzL/A7hYytFwZSxVXdtjIqtcWbk5noPWIt45UAl5Be5IItNAwA5lUbWS6vW/XUsAPQphnWMspExzG6URecnuZ+6QOFbNaXMY="

